### ISSUE TITLE
[Faucet Request]: 

### ISSUE THREAD

**Issue by Mindingo-ms** [youfoundron/cryptofaucet#27]
### Token Name

USD Coin

### Token Symbol

USDC

### Chain Title

Avalanche

### Network Title

Fuji

### Faucet URL

https://cryptofaucet.dev/

### Contract Address (optional)

0x5425890298aed601595a70AB815c96711a31Bc65

### Docs URL (optional)

https://developers.circle.com/docs/usdc-on-testnet

### Block Explorer URL (optional)

https://testnet.snowtrace.io/token/0x5425890298aed601595a70ab815c96711a31bc65

**Comment by youfoundron** [comment]
@bridgetowercapital seems this issue may have been opened by mistake :)
